# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  postgres:
    image: postgres:16-alpine
    container_name: atelier-postgres
    environment:
      POSTGRES_USER: atelier
      POSTGRES_PASSWORD: mile123_A
      POSTGRES_DB: atelier_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
